---
sidebar: sidebar 
permalink: deploy-fsx-file-system.html 
keywords: vm workloads, deploy fsx, deploy storage for vms 
summary: Después de verificar que el sistema de archivos FSx para ONTAP recomendado o sistemas de archivos en algunos casos cumple exactamente con sus requisitos, puede utilizar la fábrica de cargas de trabajo para poner en marcha el sistema en su entorno AWS. 
---
= Implementa el sistema de archivos FSx para ONTAP recomendado
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Después de verificar que el sistema de archivos recomendado FSx para ONTAP (o varios sistemas de archivos en algunos casos) cumple exactamente con sus requisitos, puede utilizar la fábrica de cargas de trabajo para poner en marcha el sistema en su entorno AWS.

Según la política y los permisos que haya añadido a su cuenta de Workload Factory, puede implementar el sistema de archivos FSx for ONTAP completamente usando Workload Factory (en modo de lectura/escritura). Si tiene menos permisos (modo de solo lectura) o ninguno (modo básico), deberá usar la información de CloudFormation de Codebox e implementar el sistema de archivos FSx for ONTAP usted mismo en AWS.

.Requisitos para implementaciones en VMware Cloud on AWS
* Debe utilizar VMware Cloud en AWS versión 1,20 o superior del centro de datos definido por software (SDDC) para implementar sistemas de archivos FSx for ONTAP.
* No se debe implementar el sistema de archivos de FSx para ONTAP en el mismo VPC que se usó durante la puesta en marcha de SDDC. En su lugar, debes ponerla en marcha en una nueva Amazon VPC de la que ya tengas para permitir la integración de VMware Cloud on AWS con Amazon FSx for NetApp ONTAP.
* Debes poner en marcha el sistema de archivos FSx para ONTAP dentro de la misma región de AWS que el SDDC.


.Pasos
. En la parte inferior de la página *Revisar plan*, seleccione *Desplegar* y se mostrará la página Crear un sistema de archivos FSX para ONTAP.
+
La mayoría de los campos que definen tu sistema de archivos FSx para ONTAP se completan en función de la información que proporcionaste, pero hay algunos campos que debes completar en esta página.

+
Puede utilizar la opción Creación rápida o Creación avanzada. Advanced Create ofrece algunos parámetros de almacenamiento adicionales que puede personalizar. https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Vea lo que ofrecen estas dos opciones"]

. *Credenciales de AWS*: Seleccione o agregue credenciales que le darán a la fábrica de cargas de trabajo los permisos necesarios para crear su sistema de archivos FSx para ONTAP directamente. También puede seleccionar el código CloudFormation de CodeBox e implementar el sistema de archivos FSx for ONTAP usted mismo en AWS.
. *Nombre del sistema de archivos*: Introduzca el nombre que desea utilizar para este sistema de archivos FSX for ONTAP.
. *Etiquetas*: Opcionalmente puedes agregar etiquetas para categorizar este sistema de archivos FSX for ONTAP.
. En la sección «Red y seguridad», introduzca la siguiente información:
+
.. *Región y VPC*: Seleccione la región y la VPC donde se implementará el sistema de archivos FSX for ONTAP.
+
Si va a implementar en VMware Cloud en AWS, asegúrese de implementarlo en una VPC que sea diferente a la VPC donde se implementa VMware Cloud en AWS.

.. *Grupo de seguridad*: Al usar la opción *Creación avanzada*, puedes seleccionar el grupo de seguridad predeterminado para la VPC FSX para ONTAP para que todo el tráfico pueda acceder al sistema de archivos FSX para ONTAP.
+
Puedes agregar una regla entrante que restrinja lo que otros servicios de AWS pueden acceder al sistema de archivos de FSx para ONTAP. Esto bloqueará la cantidad de servicios que están abiertos. Estos son los puertos y protocolos mínimos:

+
[cols="15,10,55"]
|===
| Protocolos | Puertos | Específico 


| TCP, UDP | 111 | Portmapper (se utiliza para negociar qué puertos se utilizan en solicitudes NFS) 


| TCP, UDP | 635 | NFS mountd (recibe solicitudes de montaje de NFS) 


| TCP, UDP | 2049 | Tráfico de red NFS 


| TCP, UDP | 4045 | Network Lock Manager (NLM, lockd): Gestiona las solicitudes de bloqueo. 


| TCP, UDP | 4046 | Network Status Monitor (NSM, statd): Notifica a los clientes de NFS acerca de los reinicios del servidor para la gestión de bloqueos. 
|===
.. *Zona de disponibilidad*: Selecciona la Zona de disponibilidad y la Subred.
+
Debe seleccionar la misma zona de disponibilidad que donde se instala su SDDC de VMware si desea evitar cargos por el tráfico entre zonas geográficas.

.. *Cifrado*: Al usar la opción *Advanced create*, puede seleccionar el nombre de la clave de cifrado de AWS en el menú desplegable.
.. *Control de acceso al almacén de datos*: Cuando se utiliza la opción *Advanced create*, se puede seleccionar si todos los hosts pueden acceder a los almacenes de datos o si solo ciertos nodos del clúster de vSphere en una subred específica pueden acceder a los almacenes de datos.


. En la sección «Detalles del sistema de archivos», introduzca la siguiente información:
+
.. *Credenciales de ONTAP*: Introduce y confirma la contraseña de ONTAP.
.. *Credenciales de Storage VM* (solo Advanced create): Introduzca y confirme la contraseña de Storage VM. La contraseña puede ser específica de este sistema de archivos o puede utilizar la misma contraseña introducida para las credenciales de ONTAP.


. En la sección *Resumen*, puedes ver la configuración del sistema de archivos FSx para ONTAP y del almacén de datos que el asesor de migración de VMware ha diseñado en función de tu información.
. Seleccione *Crear* para implementar el sistema de archivos FSX for ONTAP. Este proceso puede tardar hasta 2 horas.
+
Opcionalmente, en la ventana CodeBox puede seleccionar *Redirigir a CloudFormation* para crear el sistema de archivos utilizando una pila CloudFormation.

+
En cualquier caso, puede supervisar el progreso de creación en CloudFormation.



.Resultado
Se pone en marcha el sistema de archivos FSx para ONTAP.
