---
sidebar: sidebar 
permalink: deploy-fsx-file-system-evs.html 
keywords: vm workloads, deploy fsx, deploy storage for vms, evs, elastic vmware service 
summary: Después de verificar que el sistema de archivos FSx recomendado para ONTAP , o los sistemas de archivos en algunos casos, cumplen con sus requisitos exactos, puede usar Workload Factory para implementar el sistema en su entorno de AWS. 
---
= Implementa el sistema de archivos FSx para ONTAP recomendado
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Después de verificar que el sistema de archivos FSx recomendado para ONTAP (o varios sistemas de archivos en algunos casos) cumple con sus requisitos exactos, puede usar Workload Factory para implementar el sistema en su entorno de AWS.

Según la política y los permisos que haya agregado a su cuenta de Workload Factory, puede implementar el sistema de archivos FSx para ONTAP completamente usando Workload Factory (usando el modo de lectura/escritura).  Si tiene menos permisos (modo de solo lectura) o ningún permiso (modo básico), deberá usar la plantilla CloudFormation de Codebox e implementar el sistema de archivos FSx para ONTAP usted mismo en AWS.



== Requisitos

* Debe tener una suscripción a Amazon Elastic VMware Service.
* Debe tener los permisos necesarios para crear un sistema de archivos FSx para ONTAP en su cuenta de AWS.




== Consideraciones

* Puede utilizar la opción Creación rápida o Creación avanzada. Advanced Create ofrece algunos parámetros de almacenamiento adicionales que puede personalizar. https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Vea lo que ofrecen estas dos opciones"]
* En la sección "Preferencias de Amazon Elastic VMware Service", puede elegir el entorno de virtualización de EVS para conectarse a los almacenes de datos externos.  Esto rellena automáticamente algunos campos con las opciones de mejores prácticas para la implementación.  Puede modificar estas opciones según sea necesario.




== Pasos

. En la parte inferior de la página *Revisar plan*, seleccione *Desplegar* y se mostrará la página Crear un sistema de archivos FSX para ONTAP.
+
La mayoría de los campos que definen tu sistema de archivos FSx para ONTAP se completan en función de la información que proporcionaste, pero hay algunos campos que debes completar en esta página.

. En la sección "Configuración general del sistema de archivos", ingrese la siguiente información:
+
.. *Credenciales de AWS*: seleccione o agregue credenciales que le otorgarán a Workload Factory los permisos necesarios para crear su sistema de archivos FSx para ONTAP directamente.  También puede seleccionar el código CloudFormation de Codebox e implementar el sistema de archivos FSx para ONTAP usted mismo en AWS.
.. *Nombre del sistema de archivos*: Introduzca el nombre que desea utilizar para este sistema de archivos FSX for ONTAP.
.. *Etiquetas*: Opcionalmente, puede agregar etiquetas para categorizar este sistema de archivos FSx para ONTAP.


. En la sección "Preferencias de Amazon Elastic VMware Service", en la lista "ID de entorno", seleccione el entorno EVS donde se conectarán los almacenes de datos.
+
Esto rellena automáticamente los siguientes campos:

+
** *VPC*
** *Zona de disponibilidad*
** *Subred*
** En la sección *Acceso a almacenes de datos NFS*, si ha seleccionado la opción *Solo administración de host EVS*, el campo *Administración de host EVS (CIDR)* se rellena automáticamente.
** En la sección *Opciones de montaje de almacenes de datos*, si ha elegido montar los almacenes de datos en el clúster EVS, los campos *Dirección de VMware vCenter del clúster EVS* y *ARN secreto de las credenciales del administrador de vSphere* se rellenan automáticamente.


. En la sección «Red y seguridad», introduzca la siguiente información:
+
.. *Región y VPC*: seleccione la región y la VPC donde se implementará el sistema de archivos FSx para ONTAP.
.. *Grupo de seguridad* (Solo creación avanzada): Al usar la opción *Creación avanzada*, puede seleccionar el grupo de seguridad predeterminado para la VPC de FSx for ONTAP para que todo el tráfico pueda acceder al sistema de archivos de FSx for ONTAP. Puede crear un nuevo grupo de seguridad o seleccionar uno existente.
+
Si habilita la opción *Ajustar la configuración del grupo de seguridad a los almacenes de datos NFS de EVS*, Workload Factory configura el grupo de seguridad de acuerdo con las configuraciones de los almacenes de datos NFS de EVS.

+
Puede agregar una regla de entrada al grupo de seguridad que restrinja el acceso de otros servicios de AWS al sistema de archivos de FSx for ONTAP. Esto reducirá la cantidad de servicios abiertos. Estos son los puertos y protocolos mínimos:

+
[cols="15,10,55"]
|===
| Protocolos | Puertos | Específico 


| TCP, UDP | 111 | Portmapper (se utiliza para negociar qué puertos se utilizan en solicitudes NFS) 


| TCP, UDP | 635 | NFS mountd (recibe solicitudes de montaje de NFS) 


| TCP, UDP | 2049 | Tráfico de red NFS 


| TCP, UDP | 4045 | Network Lock Manager (NLM, lockd): Gestiona las solicitudes de bloqueo. 


| TCP, UDP | 4046 | Network Status Monitor (NSM, statd): Notifica a los clientes de NFS acerca de los reinicios del servidor para la gestión de bloqueos. 
|===
.. *Zona de disponibilidad*: Seleccione la zona de disponibilidad y la subred.
+
Debe seleccionar la misma zona de disponibilidad que donde se instala su SDDC de VMware si desea evitar cargos por el tráfico entre zonas geográficas.

.. *Cifrado* (solo creación avanzada): al usar la opción *Creación avanzada*, puede seleccionar el nombre de la clave de cifrado de AWS en el menú desplegable.
.. *Acceso a almacenes de datos NFS* (solo creación avanzada): al usar la opción *Creación avanzada*, puede seleccionar si todos los hosts pueden acceder a los almacenes de datos o si solo el host de administración de EVS puede acceder a ellos.


. En la sección «Detalles del sistema de archivos», introduzca la siguiente información:
+
.. *Credenciales ONTAP*: Ingrese el nombre de usuario y la contraseña de ONTAP.
.. *Credenciales de Storage VM* (solo Advanced create): Introduzca y confirme la contraseña de Storage VM. La contraseña puede ser específica de este sistema de archivos o puede utilizar la misma contraseña introducida para las credenciales de ONTAP.


. En la sección "Adjunto archivo del clúster EVS", ingrese la siguiente información:
+
.. *Opciones de montaje de almacén de datos*: de manera opcional, habilite la opción *Montar almacenes de datos en el clúster EVS* para conectar automáticamente los almacenes de datos al clúster de Amazon EVS. Esta opción también hace que Workload Factory configure los ajustes del host VMware ESXi para que coincidan con las recomendaciones de mejores prácticas de ONTAP . Antes de implementar el sistema de archivos, puede revisar los detalles del plan en la sección *Resumen* para ver las configuraciones que se cambiaron.
.. *Detalles de la consola vSphere del clúster EVS*: ingrese la dirección IP o el FQDN del servidor VMware vCenter que debe conectarse a Amazon EVS.
.. *ARN secreto de credenciales de administrador de vSphere*: elija el ARN secreto para las credenciales de administrador de vSphere.  Estas credenciales se utilizan para montar almacenes de datos y configurar los ajustes recomendados de VMware.
+
Si Amazon EVS no está disponible en esta región o si su cuenta no tiene permisos para recuperar la lista de ARN secretos disponibles, puede ingresar manualmente un valor de ARN secreto.



. En la sección *Resumen*, puedes ver la configuración del sistema de archivos FSx para ONTAP y del almacén de datos que el asesor de migración de VMware ha diseñado en función de tu información.
. Seleccione *Crear* para implementar el sistema de archivos FSX for ONTAP. Este proceso puede tardar hasta 2 horas.
+
Opcionalmente, en la ventana Codebox puede seleccionar *Redirigir a CloudFormation* para crear el sistema de archivos y la configuración de VM recomendada utilizando una pila de CloudFormation.

+
En ambos casos, puede supervisar el progreso de la creación en CloudFormation.





== Resultado

Se pone en marcha el sistema de archivos FSx para ONTAP. Ahora puede usar la plantilla de AWS CloudFormation en Codebox para implementar la configuración de VM recomendada en su entorno de Amazon Elastic VMware Service.
