---
sidebar: sidebar 
permalink: launch-migration-advisor-evs-manual.html 
keywords: overview, concepts, features, use case, workloads, how Workload Factory works, migration, manual, specification, deploy, deployment, plan 
summary: Inicie sesión en NetApp Workload Factory para acceder al centro de planificación de VMware.  Puede crear un plan de implementación para EVS manualmente. 
---
= Crear manualmente un plan de implementación para Amazon EVS
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Inicie sesión en NetApp Workload Factory para acceder al centro de planificación de VMware.  Desde allí, puede crear manualmente un plan de implementación o un plan de migración para Amazon EVS personalizado según sus necesidades.

Tenga en cuenta que debe tener un nombre de usuario y una contraseña para acceder a Workload Factory.  Si no tiene acceso, cree una cuenta ahora.  Vea las instrucciones https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["aquí"] .



== Cree un plan de implementación especificando manualmente los requisitos del entorno

Puede especificar manualmente sus requisitos para las máquinas virtuales en Amazon Elastic VMware Service y utilizar sistemas de archivos Amazon FSx para NetApp ONTAP personalizados como almacenes de datos externos.

.Requisitos
* Debe tener una suscripción a Amazon Elastic VMware Service.


.Pasos
. Inicie sesión en Workload Factory utilizando uno de los https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^] .
. De manera opcional, si accedió a Workload Factory desde la consola de Workload Factory, en el mosaico de cargas de trabajo de VMware, seleccione *VMware Planning Center* y luego seleccione *VMware Planning Center*.  Se muestra el centro de planificación de VMware.
. Seleccione *Crear plan EVS manualmente*.
. Introduzca los requisitos para su entorno de VM.
+
[NOTE]
====
Tenga en cuenta los siguientes requisitos y recomendaciones de rendimiento de migración de máquinas virtuales:

** Se recomienda una capacidad de almacenamiento mínima de 10 TiB para el inventario de VM por razones de rendimiento.
** Se requiere un rendimiento mínimo para los almacenes de datos de Amazon Elastic VMware Service, según la cantidad de IOPS requerida que especifique para esta implementación.
** Según la configuración del sistema de archivos de FSx para ONTAP, se requiere una cantidad mínima de almacenes de datos externos para que el entorno de Amazon Elastic VMware Service alcance un rendimiento óptimo.


====
. Cuando esté listo, seleccione *Revisar plan* para revisar el plan de migración.
. Revise el plan. Expande cada sección para ver los detalles del plan.
+
De forma predeterminada, Workload Factory guarda el plan de migración en el centro de planificación.  Puede deseleccionar esta opción cerca de la parte superior de la página.

. Opcionalmente, cuando esté satisfecho con el plan de migración, puede descargar los detalles del plan como un documento PDF seleccionando *Exportar plan (PDF)*.
. Cuando esté listo para aprovisionar el plan de implementación, seleccione *Aprovisionar*.


link:deploy-fsx-file-system-evs.html["Pon en marcha el sistema de archivos FSx para ONTAP recomendado para las cargas de trabajo de VMware"].
