---
sidebar: sidebar 
permalink: learn-about-vmware-workloads.html 
keywords: overview, concepts, features, use case, workloads, how Workload Factory works 
summary: 'NetApp Workload Factory para VMware proporciona herramientas para trasladar sus datos desde sistemas locales a Amazon EVS, VMware Cloud on AWS (VMC) o Amazon EC2.' 
---
= Obtenga más información sobre NetApp Workload Factory para VMware
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory para VMware proporciona herramientas para trasladar sus datos desde sistemas locales a Amazon Elastic VMware Service (EVS), VMware Cloud on AWS (VMC) o Amazon EC2.



== ¿Qué es NetApp Workload Factory para VMware?

NetApp Workload Factory para VMware ofrece un centro de planificación y asesores de migración que le permiten analizar las configuraciones actuales de sus máquinas virtuales en entornos vSphere locales.  Luego, los asesores de migración generan un plan para implementar diseños de VM recomendados en clústeres Amazon EVS, Amazon EC2 o VMware Cloud on AWS vSphere y utilizan sistemas de archivos Amazon FSx for NetApp ONTAP personalizados como almacenes de datos externos.  El centro de planificación, que actúa como el panel de Workload Factory para VMware, le permite administrar conjuntos de datos de inventario de VM guardados y planes de migración guardados, y aprovisionar cualquiera de los planes de migración que haya guardado.

Amazon FSx for NetApp ONTAP es un almacén de datos NFS externo creado en el sistema de archivos ONTAP de NetApp que se puede conectar a instancias de Amazon EVS o Amazon EC2 o a clústeres de VMware Cloud on AWS vSphere.  No es necesario agregar más hosts para aumentar el almacenamiento disponible; en su lugar, simplemente use FSx para volúmenes ONTAP como almacenes de datos externos para complementar los almacenes de datos de vSAN.  Esto le proporciona una infraestructura de almacenamiento virtualizada, flexible y de alto rendimiento que escala independientemente de los recursos informáticos.

Para obtener más información sobre Workload Factory, consulte https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Descripción general de Workload Factory"^] .



== Cómo funcionan los asesores de migración de VMware

Los asesores de migración pueden ayudarlo a trasladar máquinas virtuales (VM) locales y sus datos, que se ejecutan en cualquier almacén de datos compatible con VMware, a almacenes de datos de Amazon EVS, Amazon EC2 o VMware Cloud, que incluyen almacenes de datos NFS complementarios en un sistema de archivos FSx para ONTAP .

Ten en cuenta que puedes conectar hasta cuatro (4) FSx para volúmenes de ONTAP a un único clúster de vSphere en VMware Cloud on AWS.



== Qué puedes hacer con los asesores migratorios

Los asesores de migración proporcionan la siguiente funcionalidad:

* Analice las configuraciones actuales de máquinas virtuales en las instalaciones
* Determinar qué máquinas virtuales migrar a Amazon EC2, Amazon EVS o VMware Cloud en AWS
* Identifica el espacio necesario en FSx para volúmenes de ONTAP que se usará como almacenes de datos externos de VM
* Revise el informe resultante para comprender los pasos de despliegue
* Realizar el despliegue real


El asesor de migración admite la planificación de la configuración para una sola instancia de Amazon EVS o Amazon EC2 o un clúster de VMware Cloud on AWS conectado a un único sistema de archivos FSx para ONTAP .



== Beneficios de utilizar los asesores de migración

Pasar partes de tu infraestructura actual a Amazon EC2 o VMware Cloud on AWS mediante Amazon FSx para ONTAP como almacenes de datos NFS externos ofrece las siguientes ventajas:

* Optimización de costes gracias a la desvinculación de hosts y almacenamiento y a la eficiencia de datos avanzada
* Capacidad para aumentar la capacidad de almacenamiento según sea necesario sin necesidad de adquirir instancias de host adicionales
* Capacidades de gestión de datos de NetApp ONTAP en el cloud, como copias Snapshot con gestión eficiente del espacio, clonado, compresión, deduplicación, compactación, y la replicación
* Reducción en la gestión de las actualizaciones de hardware
* Capacidad para cambiar el rendimiento de los datos, las operaciones de IOPS y el tamaño del sistema de archivos además de aumentar o reducir el tamaño de los volúmenes
* Alta disponibilidad compatible con múltiples puestas en marcha en zonas de disponibilidad (AZ)
* Reducción del coste y de la latencia de las configuraciones de un solo AZ que utilizan pares de VPC sin necesidad de una puerta de enlace de tránsito




== Herramientas para utilizar NetApp Workload Factory

Puede utilizar NetApp Workload Factory con las siguientes herramientas:

* *Consola Workload Factory*: La consola Workload Factory proporciona una vista visual y holística de sus aplicaciones y proyectos.
* *Consola NetApp *: La consola NetApp proporciona una experiencia de interfaz híbrida para que pueda utilizar Workload Factory junto con otros servicios de datos de NetApp .
* *Pregúntame*: utiliza el asistente de IA Pregúntame para hacer preguntas y obtener más información sobre Workload Factory sin salir de la consola de Workload Factory. Accede a Pregúntame desde el menú de ayuda de Workload Factory.
* *CloudShell CLI*: Workload Factory incluye una CLI de CloudShell para administrar y operar entornos de AWS y NetApp en todas las cuentas desde una única CLI basada en navegador. Acceda a CloudShell desde la barra superior de la consola de Workload Factory.
* *API REST*: utilice las API REST de Workload Factory para implementar y administrar sus sistemas de archivos FSx para ONTAP y otros recursos de AWS.
* *CloudFormation*: use el código de AWS CloudFormation para realizar las acciones que definió en la consola de Workload Factory para modelar, aprovisionar y administrar recursos de AWS y de terceros desde la pila de CloudFormation en su cuenta de AWS.
* *Proveedor de Terraform NetApp Workload Factory*: utilice Terraform para crear y administrar flujos de trabajo de infraestructura generados en la consola de Workload Factory.




== Coste

El uso de Workload Factory para VMware no tiene ningún costo.

Deberá pagar por los recursos de AWS que implemente según las recomendaciones de los asesores de migración.



== Licencia

No se necesitan licencias especiales de NetApp para utilizar Workload Factory para VMware.



== Regiones

Workload Factory es compatible con todas las regiones comerciales donde se admite FSx para ONTAP . https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Ver regiones de Amazon compatibles."^]

Las siguientes regiones de AWS no son compatibles:

* regiones de China
* Regiones de GovCloud (EE. UU.)
* Nube secreta
* Nube de alto secreto

