---
settings:
  name: VMware workloads
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos para cargas de trabajo de VMware
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
  - title: Manos a la obra
    entries:
    - title: Obtenga más información sobre el centro de cargas de trabajo de BlueXP 
        para VMware
      url: "/learn-about-vmware-workloads.html"
    - title: Inicio rápido para migrar a Amazon EVS
      url: "/quick-start-evs.html"
    - title: Inicio rápido para migrar a Amazon EC2
      url: "/quick-start-native.html"
    - title: Inicio rápido para migrar a VMware Cloud en AWS
      url: "/quick-start.html"
  - title: Utilice el asesor de migración de VMware
    entries:
    - title: Migrar a Amazon Elastic VMware Service
      entries:
      - title: Cree un plan de despliegue con el asesor de migración
        url: "/launch-migration-advisor-evs-manual.html"
      - title: Implementa el sistema de archivos FSx para ONTAP recomendado
        url: "/deploy-fsx-file-system-evs.html"
    - title: Migrar a Amazon EC2
      entries:
      - title: Capture las configuraciones actuales de sus máquinas virtuales
        url: "/capture-vm-configurations-native.html"
      - title: Cree un plan de despliegue con el asesor de migración
        url: "/launch-onboarding-advisor-native.html"
      - title: Implementa el sistema de archivos FSx para ONTAP recomendado
        url: "/deploy-fsx-file-system-native.html"
    - title: Migrar a VMware Cloud en AWS
      entries:
      - title: Capture las configuraciones actuales de sus máquinas virtuales
        url: "/capture-vm-configurations.html"
      - title: Cree un plan de despliegue con el asesor de migración
        url: "/launch-onboarding-advisor.html"
      - title: Implementa el sistema de archivos FSx para ONTAP recomendado
        url: "/deploy-fsx-file-system.html"
      - title: Conecta FSx para ONTAP a VMware Cloud en AWS
        url: "/connect-sddc-to-fsx.html"
      - title: Migre sus datos a la nueva infraestructura
        url: "/migrate-data.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/support-registration.html"
    - title: Obtenga ayuda
      url: "/get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
