---
settings:
  name: VMware workloads
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos para cargas de trabajo de VMware
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
  - title: Manos a la obra
    entries:
    - title: Obtenga más información sobre Workload Factory para VMware
      url: "/learn-about-vmware-workloads.html"
    - title: Inicio rápido
      url: "/quick-start.html"
  - title: Utilice el asesor de migración de VMware
    entries:
    - title: Capture las configuraciones actuales de sus máquinas virtuales
      url: "/capture-vm-configurations.html"
    - title: Cree un plan de despliegue con el asesor de migración
      url: "/launch-onboarding-advisor.html"
    - title: Implementa el sistema de archivos FSx para ONTAP recomendado
      url: "/deploy-fsx-file-system.html"
    - title: Conecta FSx para ONTAP a VMware Cloud en AWS
      url: "/connect-sddc-to-fsx.html"
    - title: Migre sus datos a la nueva infraestructura
      url: "/migrate-data.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/support-registration.html"
    - title: Obtenga ayuda
      url: "/get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP Workload Factory for AWS
  repo: workload-family
