---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: Conozca las novedades del componente Asesor de migración de VMware de Workload Factory. 
---
= Novedades de NetApp Workload Factory para VMware
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Conozca las novedades del componente Asesor de migración de VMware de Workload Factory.



== 2 de noviembre de 2025



=== Presentamos las preferencias de Amazon Elastic VMware Service en el asistente de implementación del sistema de archivos FSx para ONTAP

Cuando implemente un sistema de archivos FSx para ONTAP para usarlo como almacén de datos NFS externo para Amazon Elastic VMware Service, ahora puede seleccionar el entorno EVS al que se conectarán los almacenes de datos.  Esto rellena automáticamente varios campos en el asistente de implementación para simplificar el proceso de implementación.

https://docs.netapp.com/us-en/workload-vmware/deploy-fsx-file-system-evs.html["Implementa el sistema de archivos FSx para ONTAP recomendado"]



=== Cambios de permisos para cargas de trabajo de VMware

Las cargas de trabajo de VMware ofrecen mayor claridad sobre los permisos que requieren para acciones específicas y un mayor nivel de detalle para seleccionar únicamente los permisos necesarios.  Al agregar credenciales, tendrá dos opciones de permisos para elegir en lugar del modelo de permisos anterior que era de _solo lectura_ y _lectura/escritura_. El nuevo modelo de permisos divide las políticas de permisos de la siguiente manera:

* _Visualización, planificación y análisis_: Consulte el inventario de entornos de virtualización de EVS, obtenga un análisis bien diseñado para sus sistemas y explore los ahorros.
* _Implementación y conectividad del almacenamiento de datos_: Implemente las configuraciones de máquinas virtuales recomendadas en clústeres de Amazon EVS, Amazon EC2 o VMware Cloud on AWS vSphere y utilice sistemas de archivos Amazon FSx for NetApp ONTAP personalizados como almacenes de datos externos.


Al agregar credenciales, puede seleccionar una o más de estas políticas de permisos según el nivel de acceso que desee proporcionar a las cargas de trabajo de VMware.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Referencia de permisos de Workload Factory"^]



=== Mejoras en el asesor de migración de Amazon EC2

Esta versión de NetApp Workload Factory para VMware presenta varias mejoras en la experiencia del asesor de migración:

* *Guardar o descargar un plan de migración*: Ahora puede guardar o descargar un plan de migración como archivo PDF o CSV.  Cuando guardas un plan de migración, este se guarda con tu cuenta de Workload Factory.




== 5 de octubre de 2025



=== BlueXP workload factory ahora Fábrica de cargas de trabajo de NetApp

BlueXP ha sido renombrado y rediseñado para reflejar mejor el papel que desempeña en la gestión de su infraestructura de datos. Como resultado, la BlueXP workload factory pasó a llamarse Fábrica de carga de trabajo de NetApp .



=== Presentamos el centro de planificación de cargas de trabajo de VMware

El centro de planificación de cargas de trabajo de VMware le permite ver y administrar su inventario de máquinas virtuales y sus planes de migración desde un solo lugar.  Puede cargar y guardar múltiples inventarios de VM de diferentes entornos y comenzar a planificar una migración al servicio AWS EC2 o Amazon Elastic VMware para cualquiera de ellos.  También puede crear y guardar planes de migración de AWS EC2 o EVS.

https://docs.netapp.com/us-en/workload-vmware/explore-planning-center.html["Explorar el centro de planificación de cargas de trabajo de VMware"]



=== Presentamos el soporte del asesor de migración para Amazon Elastic VMWare Service

BlueXP Workload Factory para VMware ahora le permite utilizar el asesor de migración de Amazon Elastic VMware Service para migrar rápidamente sus cargas de trabajo de VMware locales a Amazon Elastic VMware Service.  Después de crear un plan de migración utilizando el asesor de migración, este se guarda automáticamente en la lista de planes de migración en el centro de planificación.

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs.html["Cree un plan de implementación para Amazon EVS utilizando el asesor de migración"]



== 3 de agosto de 2025



=== Soporte mejorado del asesor de migración para Amazon Elastic VMWare Service

NetApp Workload Factory ahora admite la implementación y el montaje automáticos de su sistema de archivos Amazon FSx for NetApp ONTAP .  Esto le permite comenzar a implementar sus máquinas virtuales en FSx para sistemas de archivos ONTAP cuando se complete la migración al entorno de Amazon EVS.

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["Cree un plan de implementación para Amazon EVS utilizando el asesor de migración"]



=== Calcule el ahorro de costos al migrar a Amazon Elastic VMware Service

Ahora puede explorar los ahorros potenciales que obtendrá al migrar sus cargas de trabajo de VMware a Amazon Elastic VMware Service (EVS).  La calculadora de ahorros le permite comparar los costos de usar Amazon EVS con y sin Amazon FSx for NetApp ONTAP como almacenamiento subyacente.  La calculadora muestra ahorros potenciales en tiempo real a medida que ajusta las características de su entorno.

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["Explore los ahorros de Amazon Elastic VMware Service con BlueXP Workload Factory"]



== 29 de junio de 2025



=== Presentamos el soporte del asesor de migración para Amazon Elastic VMWare Service

BlueXP Workload Factory para VMware ahora es compatible con Amazon Elastic VMware Service. Puede migrar manualmente sus cargas de trabajo de VMware locales a Amazon Elastic VMware Service, lo que optimiza los costos y permite un mayor control sobre su entorno VMware sin necesidad de refactorizar o cambiar la plataforma de sus aplicaciones.

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["Cree un plan de implementación para Amazon EVS utilizando el asesor de migración"]



== 4 de mayo de 2025



=== Mejoras en el asesor de migración de Amazon EC2

Esta versión de BlueXP Workload Factory para VMware presenta la siguiente mejora en la experiencia del asesor de migración de Amazon EC2:

* Información sobre la infraestructura de datos de NetApp como fuente de datos *: La fábrica de cargas de trabajo ahora se conecta directamente con la información sobre la infraestructura de datos de NetApp para recopilar información sobre la implementación de VMware cuando utiliza el recopilador de datos del asesor de migración EC2.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Cree un plan de implementación para Amazon EC2 con el asesor de migración"]



=== Terminología de permisos actualizada

La interfaz de usuario y la documentación de Workload Factory ahora usan "solo lectura" para referirse a los permisos de lectura y "lectura/escritura" para referirse a los permisos automatizados.



== 30 de marzo de 2025



=== Mejoras en el asesor de migración de Amazon EC2

Esta versión de BlueXP Workload Factory para VMware presenta varias mejoras en la experiencia del asesor de migración de Amazon EC2:

* *Guía mejorada para la asignación de volúmenes*: La información de asignación de volúmenes en los pasos “Clasificar” y “Paquete” del asesor de migración EC2 ofrece una mayor legibilidad y usabilidad. Se muestra información más útil sobre cada volumen, lo que permite identificar mejor los volúmenes y determinar cómo asignarlos.
* * Mejoras de la eficiencia de los scripts de recopilación de datos*: El script recopilador de datos del asesor de migración EC2 optimiza el uso de la CPU al recopilar datos para implementaciones de máquinas virtuales más pequeñas.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Cree un plan de implementación para Amazon EC2 con el asesor de migración"]



== 2 de marzo de 2025



=== Mejoras en el asesor de migración de Amazon EC2

Esta versión de BlueXP Workload Factory para VMware presenta varias mejoras en la experiencia del asesor de migración de Amazon EC2:

* *Tipo de instancia estimado*: El asesor de migración ahora puede examinar los requisitos de su entorno y proporcionar un tipo de instancia estimado de Amazon EC2 para cada VM. Puede optar por incluir el tipo de instancia estimado para cada máquina virtual durante el paso de alcance del asesor de migración.
* *Posibilidad de recomendar volúmenes de Amazon EBS*: El asesor de migración ahora puede recomendar migrar volúmenes de datos a Amazon Elastic Block Store (EBS) en lugar de Amazon FSx para NetApp ONTAP debido a las necesidades específicas de capacidad o rendimiento de una determinada región.
* *Asignación automática del sistema de archivos mejorada*: La asignación del sistema de archivos de Amazon FSx para NetApp ONTAP se ha mejorado para optimizar mejor el costo y minimizar el rendimiento.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Cree un plan de implementación para Amazon EC2 con el asesor de migración"]



== 5 de enero de 2025



=== Mejoras en el asesor de migración de Amazon EC2

Esta versión de BlueXP Workload Factory para VMware presenta varias mejoras en la experiencia del asesor de migración:

* *Guardar o descargar un plan de migración*: ahora puede guardar o descargar un plan de migración y cargarlo para completar el asesor de migración.  Cuando guarda un plan de migración, este se guarda con su cuenta de Workload Factory.
* *Selección de VM mejorada*: BlueXP Workload Factory para VMware ahora admite el filtrado y la búsqueda en la lista de VM que desea incluir en su implementación de migración.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Cree un plan de implementación para Amazon EC2 con el asesor de migración"]



== 1 de diciembre de 2024



=== Mejoras en el asesor de migración de Amazon EC2

Esta versión de NetApp Workload Factory para VMware presenta varias mejoras en la experiencia del asesor de migración:

* *Recopilación de datos*: BlueXP Workload Factory para VMware admite la capacidad de recopilar datos durante un período de tiempo específico cuando utiliza el asesor de migración.
* *Selección de VM*: BlueXP Workload Factory para VMware ahora permite seleccionar las VM que desea incluir en su implementación de migración.
* *Experiencia rápida frente a avanzada*: Cuando utiliza el asesor de migración, ahora puede elegir una experiencia de migración rápida, utilizando RVtools, o la experiencia avanzada, que utiliza el recopilador de datos del asesor de migración.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Cree un plan de implementación para Amazon EC2 con el asesor de migración"]



== 3 de noviembre de 2024



=== Ayuda de la relación de reducción de datos del asesor de migración de VMware

Esta versión de Workload Factory para VMware cuenta con un asistente de reducción de la tasa de datos. El asistente de la relación de reducción de datos te ayuda a decidir qué relación es la mejor para tu inventario de VMware y el estado de almacenamiento cuando se prepara para la incorporación de cloud AWS.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Cree un plan de implementación para Amazon EC2 con el asesor de migración"]



== 19 de septiembre de 2024



=== Mejoras en el asesor de migración de VMware

Esta versión de Workload Factory para VMware presenta mejoras de funcionalidad y estabilidad, así como la capacidad de importar y exportar planes de migración al utilizar el asesor de migración de VMware.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Cree un plan de implementación para Amazon EC2 con el asesor de migración"]



== 1 de septiembre de 2024



=== Migrar a Amazon EC2

El centro de cargas de trabajo para VMware admite ahora la migración a Amazon EC2 mediante el asesor de migración de VMware.



== 7 de julio de 2024



=== Lanzamiento inicial de Workload Factory para VMware

La versión inicial incluye la capacidad de utilizar el asesor de migración de VMware para analizar tus configuraciones actuales de máquinas virtuales en entornos vSphere on-premises y generar un plan para implementar diseños de máquinas virtuales recomendados en VMware Cloud on AWS y utilizar los sistemas de archivos personalizados de Amazon FSx para NetApp ONTAP como almacenes de datos externos.
